apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: ember-csi-snap
spec:
  volumeSnapshotClassName: backend.ember-csi.io
  source:
    persistentVolumeClaimName: ember-csi-pvc

